### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by dotaxis**
As per this issue:
https://github.com/tsunamods-codes/7th-Heaven/issues/157

Credit to @nuadaxxx

I have not double-checked the translations as I do not know the language.

### CODE REVIEW

**Review by nuadaxxx — APPROVED** [review]
Cant see a problem for now ! Only a PR shark :)

**Comment by dotaxis** [comment]
> Cant see a problem for now ! Only a PR shark :)

Just trying to help since you couldn't figure it out.

**Comment by nuadaxxx** [comment]
How long does it need to insert it in the new build ?

**Comment by eve-atum** [comment]
A diff this big takes time to review... be patient.

**Comment by dotaxis** [comment]
@nuadaxxx learned how to open a PR

**Pull request closed without merging**
