### PR TITLE
UI: Tweak driver upgrade/downgrade message

### PR DESCRIPTION
**Pull request by eve-atum**
Remind users to reconfigure their driver after upgrading/downgrading FFNx.  We get this question often enough, and Kuraudo asked nicely...

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Thanks for the PR :) Despite the good intentions there I'd like to have a bit more professional message and if possible added here instead which is the last message the user will see after FFNx has been updated: https://github.com/tsunamods-codes/7th-Heaven/blob/master/SeventhHeavenUI/Classes/FFNxDriverUpdater.cs#L261

Also I think something like "Settings have been reset to default" is enough to let the users know about this. No need to add any hint or pointer to reconfigure them, they'll understand it.

If you can please rework your PR, I'll be happy to review. Thanks!

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
Thanks for the PR :) Despite the good intentions there I'd like to have a bit more professional message and if possible added here instead which is the last message the user will see after FFNx has been updated: https://github.com/tsunamods-codes/7th-Heaven/blob/master/SeventhHeavenUI/Classes/FFNxDriverUpdater.cs#L261

Also I think something like "Settings have been reset to default" is enough to let the users know about this. No need to add any hint or pointer to reconfigure them, they'll understand it.

If you can please rework your PR, I'll be happy to review. Thanks!

**Comment by eve-atum** [comment]
Moved over to where you suggested

**Review by julianxhokaxhiu — APPROVED** [review]
LGTM

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Pull request merged**
