### PR TITLE
Update 7H_GameDriver_UI.de.xml

### PR DESCRIPTION
**Pull request by nuadaxxx**
Text too Long, just a little fix

Problem = https://ibb.co/5WR578y

 FIX  = https://ibb.co/s6Kcyxh

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
@eve-atum can you please review?

**Comment by eve-atum** [comment]
Sent PR#171 to include both nuadaxxx's fix, as well as add him, jtd, and vyzz to the translation credits in help\index.html

**Comment by julianxhokaxhiu** [comment]
Merged as part of #171

**Comment by nuadaxxx** [comment]
> Sent PR#171 to include both nuadaxxx's fix, as well as add him, jtd, and vyzz to the translation credits in help\index.html

Thanks, but would be nice if u use only Nuada not xxx, like in the Qhimm discord.

And i see this, not sure if that was intended. -  https://ibb.co/nbR3t7w

Have a nice day.

**Pull request closed without merging**
