### PR TITLE
Footstep Toggle Foreign Language & UpdateChecker Grammar

### PR DESCRIPTION
**Pull request by wturner859**

### CODE REVIEW

**Comment by wturner859** [comment]
Wanting to get CM out in a couple days. Think we can get this put in by then?

**Comment by julianxhokaxhiu** [comment]
FYI you might want to drop the commit https://github.com/tsunamods-codes/7th-Heaven/pull/29/commits/465f6e1f62bf75c19f2d245b9f6861ba9f6447fb in favor of #34 

This should provide your own mod the ability to autoconfigure the user environment and ensure it will always work no matter what :)

**Comment by barkermn01** [comment]
I would tend to agree but I would like @wturner859's opinion, see if he can make a mod that will do this using the new Canary :D

**Comment by wturner859** [comment]
Problem with that is if I add the "footsteps=true" to my mod.xml, it would be an "always on" thing... There's no way for the user to decide if they want them or not.
It's nice for being able to automatically set audio.dat to VGMStream, but not so much for footsteps.

**Comment by julianxhokaxhiu** [comment]
Understood. I'm not sure how the 7th mod.xml conditionals work for that layer so we might check that and implement accordingly to allow you configure the driver, depending on what your mod configuration looks like.

Regarding #28 you've deleted the repo so it was impossible to merge it anyway. Therefore please add that same change in this PR. Thank you.

**Comment by wturner859** [comment]
Currently, since the footsteps feature is just re-routed sound 159's, the footsteps are just files included with the rest of the regular sounds... If I made a folder of just footstep sounds and made it conditional in the mod config (like I do for UI sounds or whatever) and then turned it off so that all the new sounds effectively aren't in the game, the game would just fall back on to the original 159 on every field (assuming footsteps=true) and still play footsteps... What we would need is essentially the toggle submitted in this PR itself to be toggleable in the mod config by the user, or for footsteps=true ONLY if a certain mod option is on, not if the mod is just active. something like: 
`  <FFNxConfig>
    <use_external_sfx>true</use_external_sfx>
		<ActiveWhen>
             <And>
              <Option>Footsteps = 1</Option>
             </And>
         </ActiveWhen>
  </FFNxConfig>`

**Comment by barkermn01** [comment]
@julianxhokaxhiu @wturner859 i would hope this would work using the options system that we currently have, where the options get present in a UI when you double click on them may be a dedicated section for FFNx controls, the same as like ESUI and such, we provide users with the options?

**Comment by wturner859** [comment]
> @julianxhokaxhiu @wturner859 i would hope this would work using the options system that we currently have, where the options get present in the mod settings UI when you double click on them may be a dedicated section for FFNx controls, the same as like ESUI and such, we provide users with the options?

That's essentially what we have with with driver settings and what this PR was for in the first place, kind of, right?... Also I just realized, where this footstep feature isn't just a Cosmo Memory feature and can be used without mods, whether we get this auto-toggle working or not, would it not still make sense to have the submitted toggle placed in those driver settings for those people?

**Comment by barkermn01** [comment]
Sorry I updated my based on your updates, so removed that comment @wturner859 if your want to reply your more than welcome to :D

**Comment by wturner859** [comment]
> @julianxhokaxhiu with the above, while I like the idea think it's badly formatted in terms of adding size to a mod.xml and parsing speeds, but would something like
> 
> ```
> <FFNxConfig>
>     <ff7_footsteps option="footsteps">true</ff7_footsteps>
> </FFNxConfig>
> ```
> 
> So that when the option attribute is present it uses that option if that option exists otherwise defaults to the value inside the tag in this case true,
> 
> This means the default options system works, and can feed the values into the FFNx Config

Mod options are either in an "off" or "on" state (or a list of more than 2 options)
It would need to know that the mod option "footsteps" is "on" before it turns FFNx to true, not just that the the option is present, otherwise we're where we started.
so maybe:
```
> <FFNxConfig>
>     <ff7_footsteps option="footsteps=1">true</ff7_footsteps>
> </FFNxConfig>
```

**Comment by barkermn01** [comment]
> > @julianxhokaxhiu with the above, while I like the idea think it's badly formatted in terms of adding size to a mod.xml and parsing speeds, but would something like
> > ```
> > <FFNxConfig>
> >     <ff7_footsteps option="footsteps">true</ff7_footsteps>
> > </FFNxConfig>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So that when the option attribute is present it uses that option if that option exists otherwise defaults to the value inside the tag in this case true,
> > This means the default options system works, and can feed the values into the FFNx Config
> 
> Mod options are either in an "off" or "on" state (or a list of more than 2 options)
> It would need to know that the mod option "footsteps" is "on" before it turns FFNx to true, not just that the the option is present, otherwise we're where we started.
> so maybe:
> 
> ```
> > <FFNxConfig>
> >     <ff7_footsteps option="footsteps=1">true</ff7_footsteps>
> > </FFNxConfig>
> ```

No the options are controlled by the user by double-clicking on a mod in 7th heaven, so you point it at the option has a default value but the user can override the default value so in your footsteps mod you would create the option, and then tell the FFFNx to use that option's value, if you look at `Qhimm - Gameplay Mod` so install it then double click on it you will see how the options system works in 7th heaven

**Comment by wturner859** [comment]
I'm aware how 7h's mod options system works. I don't need to download gameplay. I've made several mods with more complex configs than gameplay lol... I think you're confused as this isn't a "footsteps mod" we're talking about... the footsteps are just a feature of a much larger mod which can turned on or off, and _only if that particular footstep option is turned on_ would we want ffnx to turn footsteps on.

**Comment by barkermn01** [comment]
> I'm aware how 7h's mod options system works. I don't need to download gameplay. I've made several mods with more complex configs than gameplay lol... I think you're confused as this isn't a "footsteps mod" we're talking about... the footsteps are just a feature of a much larger mod which can turned on or off, and _only if that particular footstep option is turned on_ would we want ffnx to turn footsteps on.

Ok, I don't know who you are or what your level is so I'm making sure to explain everything I'm saying and give examples, there is also the fact that this might become a reference for other people it is public after all so step of your high horse.

but also you don't seem to understand how a pointer to another value would work and that's all I'm saying is we tell the FFNx config parser that if the attribute `option` is present use the value from the ConfigOption that the attribute's value matches to the ID of said Config Option.

**Comment by wturner859** [comment]
I'm Bonez

**Comment by julianxhokaxhiu** [comment]
Calm down everyone.

@barkermn01 got your point and i'll look into this layer later, in order to see if I can filter out config flags matching Options. If yes, then every modder could use the syntax you suggested to apply a config only if an option is enabled.

@wturner859 calm down, and give us some time to discuss about improvements and ways to tackle this. We are aiming in hiding "trivial" flags in a much smarter way which will allow modders like you to govern that behavior, on top of users choice.

Having that flag added in the panel like you are suggesting might solve your issue, but not ours.

Work with us, instead than on top of us.

**Pull request closed without merging**
