### PR TITLE
FFNx: Improve the overall configuration management lifecycle

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
- Expose a new class that centralizes all the logic management: FFNxConfigManager
- The configuration can now be accessed via Sys.FFNxConfig
- 7th Defaults ( inherited from the Game Driver UI xml files ) will be automatically set on each driver update

### CODE REVIEW

**Comment by barkermn01** [comment]
Just a quick question, as it might be easy for you to do it, if it is would be quite cool if it could, 

> 7th Defaults ( inherited from the Game Driver UI xml files ) will be automatically set on each driver update

Would it be possible to add a button that is "save as default", that overwrites the default config file?

**Comment by julianxhokaxhiu** [comment]
> Would it be possible to add a button that is "save as default", that overwrites the default config file?

I've never thought about this scenario, but now that we have a new centralized manager I think we can go crazy creative. My idea is that after this PR I wanted to introduce the ability to override FFNx config values through a mod.xml manifest.

It comes natural that users can afterwards then build their own mod.xml with their own desired configuration and put it on top of the list, so when the 7th will launch the game will:

-> load the current `FFNx.toml`
-> apply user desired config ( own user mod.xml )
-> apply mod desired config ( catalog mods )
-> launch the game

This way we will most probably not need to build it in 7th, but probably create a Wizard to create those user custom mods.

There are for sure other ways to tackle this solution, but this is the one that comes in my mind as, once we implement the ability to override FFNx settings through `mod.xml`, the "per-user" implementation comes literally for free.

**Comment by barkermn01** [comment]
> There are for sure other ways to tackle this solution, but this is the one that comes in my mind as, once we implement the ability to override FFNx settings through mod.xml, the "per-user" implementation comes literally for free.

Okies that sounds awesome, 

Just looking at 
```c#
public void Reload()
        {
            if (File.Exists(_pathToFFNxToml)) _toml = Toml.Parse(File.ReadAllBytes(_pathToFFNxToml)).ToModel();
        }
```

What happens if it does not find the file does it cause an exception later on or just assume defaults?

Or should it have an else on the reload, that calls `ResetTo7thHeavenDefaults()` and `Save()` so if someone cocks up their settings they can just delete the file and it creates the default for them?

**Comment by julianxhokaxhiu** [comment]
> > There are for sure other ways to tackle this solution, but this is the one that comes in my mind as, once we implement the ability to override FFNx settings through mod.xml, the "per-user" implementation comes literally for free.
> 
> Okies that sounds awesome,
> 
> Just looking at
> 
> ```cs
> public void Reload()
>         {
>             if (File.Exists(_pathToFFNxToml)) _toml = Toml.Parse(File.ReadAllBytes(_pathToFFNxToml)).ToModel();
>         }
> ```
> 
> What happens if it does not find the file does it cause an exception later on or just assume defaults?
> 
> Or should it have an else on the reload, that calls `ResetTo7thHeavenDefaults()` and `Save()` so if someone cocks up their settings they can just delete the file and it creates the default for them?

The idea of that check is simply because the `Reload()` method is called when the class is created. Although it might be someone is doing a fresh install and FFNx is (yet) not there. That check will silently fail, but it will guaranteed to work when:
-> Installing FFNx with check for updates manually or,
-> Installing FFNx automatically when clicking Play

In either case, the configuration will be reloaded as the file will exist. If someone deletes the FFNx.toml manually, at the moment there's no fallback and the installation will be considered corrupted. There was never before, nor it's there now, a way to recover from such scenario.

Feel free to come up with an idea if you want to support it :)

**Review by barkermn01 — COMMENTED** [review]
Approved

**Pull request merged**
