### PR TITLE
Added Project for auto updater and Setup

### PR DESCRIPTION
**Pull request by barkermn01**
Added support for an Updater and setup tools.

1) Setup Project added
    a) UAC Request button after setup has opened
    b) Identifies Steam installs of 7th heaven and preloads FF7 path
    c) has support for ff7.exe, ff7_en.exe, and other regions following the same format
    d) uses Updater project
2) Updater Project
    a) uses GitHub API to make requests to get the latest release build
    b) has support different tags from git hub, supported tags are "alpha", "beta", "canary", "stable"
    c) allows CLI params to control installed update (updater.exe {path_to_ff7} {release_tag}
    d) will autorun 7th heaven after an update is installed
    
    
Work to be done to the main 7th heaven application :
When update notice is given about update remove usage of catalog style downloading system, and instead just open updater.exe and shutdown 7th heaven application allowing the updater to run, and update files.

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
This PR is amazing, thanks! For me is good to go, the only thing I'd do is forcing the channels to be only canary and stable, as we don't have the capacity to handle alpha and beta, and this might confuse users even more.

Additionally to this PR another one also should follow which should run this updater.exe and closes 7th main app when the user says yes, although we must find a way to pass some parameters to the updater to auto-launch it with the channel and version set, so the user really updates to the version proposed in the 7th app when prompted.

Great job so far!

**Comment by barkermn01** [comment]
"the only thing I'd do is forcing the channels to be only canary and stable", it does not need doing really, because if someone tries to use them it will error out due to the API not having the information, so technically the GitHub API is forcing them and then the setup only actually supports "Stable", so if they wanted to install canary at the moment they would have to use the setup and manually run the command to get canary (which I'm not sure I mind because canary users should know how to use CLI tools / be told how to install the canary build if it's to explicitly test something) but not sure how  feel.

I could add a drop-down option box to the setup project to allow it to pick Stable or Canary, if we wanted to give people the option easily, might just be that I have to also Write a JSON file out to the setup path saying.

```json 
{
"current_version":"",
"current_channel":"stable"
}
```

So the in-app update checker can go what channel am I looking at updates for?

**Comment by julianxhokaxhiu** [comment]
Fine by me! If we can have CLI params it would be the best, so I can just start the process and let it handle everything. Feel free to let me know which will be those params and I'll be happy to implement the in-place update on 7th once the user clicks Yes on the update notification!

**Comment by barkermn01** [comment]
> Regarding the Update, I thought it has a window gui, but if not then feel free to leave the code in place, might be useful in the future.

It does but only to show its progress bar for download/extraction, does not provide users any ability to control what they are downloading the calling application does that, whether it's Command Prompt / Powershell, Setup or 7thHeavenGUI

So will update the Setup, and Updater to honor the JSON file method. will get that done as soon as I can.

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Comment by barkermn01** [comment]
@julianxhokaxhiu okies added support for the updater.json file for you so you should be able to use it in the main UI app

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
So far looks good, but I still miss couple of things. I left you some comments on Discord.

Thanks!

**Comment by barkermn01** [comment]
Can you create a build of this latest version that I can test with, and build the express SED file?

**Comment by julianxhokaxhiu** [comment]
Good to go for me, but we need to fix CI issues in order to merge this PR.

**Pull request merged**
