### PR TITLE
Change crash zip location.

### PR DESCRIPTION
**Pull request by wturner859**
Still easy for users to find. Less intrusive.

### CODE REVIEW

**Comment by chrcoluk** [comment]
The change makes sense I have had feedback as well from the community that the desktop zips are a bit intrusive.

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by wturner859** [comment]
I see. Yeah, if the path is going to automatically pop up if they click yes, that's cool. I was worried that the workshop folder would be too difficult for them to find... Then again, just changing it to documents as a permanent solution is both easy for the end users to find and less work for you. I'm cool either way.

**Comment by julianxhokaxhiu** [comment]
Ok I'll pick path 1 so for the time being at least users don't get it on the Desktop. Thanks!

**Comment by wturner859** [comment]
Yeah. I get a crash zip on literally every close of the game. So my desktop thanks you.

**Pull request merged**
