### PR TITLE
Support lightweight build mode

### PR DESCRIPTION
**Pull request by TurBoss**
Work in progress

This is a very early status of the idea i have to allow gamedev to customice 7h for their mod

forn now it only hides some elements depending on build options aka "conditional symbols"

TODO:
- [x] add a button to check for game content updates and promt to download
- [x] and the posiblity to add a custom 7heaven.var file
- [ ] add a big picture behind all the controls customizable from theme

Thanks

### CODE REVIEW

**Comment by TurBoss** [comment]
I don't really know how to achieve the TODO :D

**Comment by julianxhokaxhiu** [comment]
Fixed the syntax for you :) Feel free to tweak it at your own desire, and before saving use the Preview tab to double check.

Thank you for this amazing PR! Looking forward to see this implemented upstream.

**Comment by barkermn01** [comment]
@TurBoss how has this come have you been able to fix it?

**Comment by TurBoss** [comment]
yup I'm done Thanks all

**Comment by TurBoss** [comment]
I think this PR could be closed ?

**Pull request closed without merging**
