### PR TITLE
Added support for mods to use mod.xml to add variables to the .var fi…

### PR DESCRIPTION
**Pull request by barkermn01**
allowing mod creators to use the below XML snippet inside their mod.xml so no more shipping of 7thHeaven.var files and users trying to manually manage files, these are loaded and unloaded with mods, the code also allows 7th heaven to keep a cache of the base file (moved to resources) so when doing overwrites in memory it's not re-reading a file that should not be changed

```xml
<Variable name="VarName">
  <Value>Int:0x00000000:0x10000000</Value>
</Variable>
```

### CODE REVIEW

**Comment by barkermn01** [comment]
@TurBoss

**Comment by barkermn01** [comment]
Added Support for mod compatibility check when they are using variables now, this needs a bit more testing before I merge it into the code base @julianxhokaxhiu would you mind having a quick test of this before I release it into the canary build?

**Comment by julianxhokaxhiu** [comment]
As soon as I have back a working internet connection at home, i'll be happy to do so. Please assign to me so I do not forget, thank you!

**Review by julianxhokaxhiu — APPROVED** [review]
Tested and works like a charm. Code wise I think you nailed it the best way you could. Good to go for me. Thank you!

**Pull request merged**
