### PR TITLE
Grammatical errors in UpdateChecker.cs

### PR DESCRIPTION
**Pull request by wturner859**

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Probably Visual Studio re-indentations. If you can manage to rework the patch it would be appreciated so we have a commit changing only these two lines :)

Thank you!

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
Probably Visual Studio re-indentations. If you can manage to rework the patch it would be appreciated so we have a commit changing only these two lines :)

Thank you!

**Comment by wturner859** [comment]
Apparently I can't... "We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF)."

**Comment by julianxhokaxhiu** [comment]
> "We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF)."

Just hit No and you'll be good to go! There should be one commit doing only this action in order to uniform the entire project.

@barkermn01 you might consider adding this into your TODO list FYI

**Comment by barkermn01** [comment]
Not sure why this is Git is supposed to normalize all line endings on the pull or push... push is supposed to normalize to Unix site (`\n`) and pull normalize to your OS's line endings so Mac (`\r`) and windows (`\r\n`)

**Pull request closed without merging**
